### ISSUE TITLE
Request - Local Music-Player instead of "Netease"

### ISSUE THREAD

**Issue by MickLesk** [SHIMLY-GitHub/flutter_music#2]
Hey Guy,

I think your app looks really nice, but I wonder why every second git project runs with "Netease". This is not really popular in Europe.
Have you ever thought about building your app for "local" music? That is, for the music that is stored in the memory and doesn't run through the Netease cloud.

What do you think?

**Comment by coder-dongjiayi** [comment]
@MickLesk 我并没有打算商业化这个项目，因为没有音乐版权，所以就直接用别人写好service 也就是"Netease"
